- frontend/src/App.jsx
- frontend/src/components/jsPDF.jsx
- frontend/src/index.css
- frontend/src/pages/Login.jsx
- frontend/src/pages/Raspored.jsx
Samo sam na jedan element dodao margine i umjesto običnog fetcha koristio sam axios. Osim toga sam samo napravio neke manje zanemarive izmjene.
> Napravljene male izmjene u frontendu

- backend/errorKodovi.js
- backend/server.js
U backend dio je dodano spajanje na PostgreSQL bazu podataka. Sad se preko servera mogu dohvaćati podaci iz bilo koje tablice (ili svi ili od onih sa željenim ID-om). Dodan je i modul za "error kodove".
> Implementirano spajanje na bazu podataka preko API-ja

- Potrebne instalacije.txt
- backend/package-lock.json
- backend/server.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/Login.jsx
Unutar koda za frontend (Login) i backend (server) je implementirana funkcionalnost logiranja. 
Nadodan dokument Potrebne instalacije.txt koji sadrži sve sto je potrebno da se frontend i backend mogu pokrenit.
Preporučeno da se testira prije odobrenja.
> Implementiran funkcionalni Login za Studenta

- backend/server.js
- frontend/src/hooks/useLogin.js
Unutar servera je nadodan kod za dohvat termina. Terminin se dohvaćaju ovisno o studju studneta, a obavlja se preko email-a od studenta.
Mozete testirati unutar postmana na sljedeci način:
POST http://localhost:3000/raspored
Body: raw
{
"email": "petra.petrovic@univ.com"
}
i odvojeno neki drugi email
{
"email": "ivan.ivic@univ.com"
}
> Nadodan funkcionalni dohvat termina ovisno o studiju prijavljenog studenta (trenutacno samo u backendu)

- backend/src/routes/generalRoutes.js
- backend/src/routes/korisnikRoutes.js
- backend/src/utils/errorKodovi.js
- backend/src/utils/userTypeMiddleWare.js
- backend/src/viewModels/generalViewModel.js
- backend/src/viewModels/korisnikViewModel.js
- frontend/src/viewModels/useLogin.js
- frontend/src/views/Login.jsx
Dodana je mogućnost profesorima, ono što je prije bilo samo moguće studentima (login, pregled rasporeda, pregled ostalih grupa).
> Dodane funkcionalnosti aplikacije profesorima

- frontend/package-lock.json
- frontend/package.json
- frontend/src/__tests__/App.test.jsx
- frontend/src/__tests__/Button.test.jsx
- frontend/src/__tests__/Login.test.jsx
- frontend/vite.config.js
> dodan test za button.jsx

- frontend/src/css/Raspored.css
- frontend/src/redux/userSlice.js
- frontend/src/viewModels/useLogin.js
- frontend/src/views/Raspored.jsx
dodani u redux stanje svi termini i notes, svi termini implementirani notes ce biti u iducem nakon izrade route, promijenjen todo lista iz ul li u textarea radi lakše logike i spremanja u bazu
> dodani svi termini

- backend/__tests__/errorKodovi.test.js
- backend/package-lock.json
> testovi za backend

- backend/src/routes/korisnikRoutes.js
- backend/src/viewModels/korisnikViewModel.js
- frontend/src/redux/userSlice.js
- frontend/src/viewModels/useLogin.js
- frontend/src/views/Raspored.jsx
kolega reiu uporno potkopava moj rad mislim da bi bilo uredu kada bi ga izbacili it tima.....stanje notesa se dohvaca iz baze i prikazuje na ekranu....također ispravljen kod u backendu sto je zapravo posao bivseg kolege reia
> redux notes

- backend/__tests__/dozvoljenetablice.test.js
dodani testovi za dozvoljenetablice.js
> dodani testovi za dozvoljenetablice.js

- frontend/src/css/Raspored.css
- frontend/src/redux/userSlice.js
- frontend/src/viewModels/useLogin.js
- frontend/src/views/Raspored.jsx
prikaz kolokvija zamišljen s pop upom jer prikaz svih informacija odjednoom zauzima previse mista
> prikaz kolokvija

- backend/__tests__/prijevodDana.test.js
- backend/__tests__/provjeraFormata.test.js
- backend/package-lock.json
- backend/package.json
> backend testovi

- backend/src/routes/korisnikRoutes.js
- backend/src/utils/errorKodovi.js
- backend/src/viewModels/korisnikViewModel.js
Trenutacno je samo nadodana samostalna razmjena termina za profesore u backendu.
Pokušat ću nadodati još mogućnost slanja zahtjeva razmjena između profesora, ali nikaj ne mogu obećat jer mi je za samo ovo tribalo dosta vrimena, a triban učit numeričku.
Evo ako vas zanima priko postman-a da mozete lakše testirat funkciju.
{
"profesor_email": "marko.markovic@univ.com",
"kolegij_naziv": "Osnove programiranja - Predavanja",
"dan_u_tjednu": "Srijeda",
"pocetak": "8:15",
"kraj": "10:00"
}
> Nadodana samostalna razmjena termina za profesora

- backend/src/viewModels/korisnikViewModel.js
- frontend/src/views/Raspored.jsx
dodana promjena grupe ukoliko kapacitet nije popunjen,sljedece kada je popunjen i direktno slanje zahtjeca korisniku,manje promjene u backendu zbog grupa_id
> promjena grupe ukoliko je slobodno

- backend/__tests__/generalViewModel.test.js
- backend/package-lock.json
- backend/package.json
zapoceti testovi za generalViewModel.js
> dodan generalViewModel.test plus zapoceti testovi

- backend/__tests__/korisnikViewModel.test.js
- backend/package-lock.json
- backend/package.json
dodani testovi za korisnikviewmodel
> dodani testovi za korisnikviewmodel

- backend/src/viewModels/korisnikViewModel.js
- frontend/src/css/Raspored.css
- frontend/src/redux/userSlice.js
- frontend/src/viewModels/useLogin.js
- frontend/src/views/Raspored.jsx
promjena grupe kad aje kapacitet popunjen slanjem zahtjeva,zahtjev nakon štp je prihvace ili odbijen ostaje vidljiv dok se pononvo ne refresha stranica odnosno ne izmijeni vrijednost reduxa
> razmjena s zahtjevom

- .gitignore
- backend/.env.example
- backend/package-lock.json
- backend/package.json
- backend/src/models/baza/mock unosi.txt
- backend/src/models/pool.js
- backend/src/routes/korisnikRoutes.js
- backend/src/utils/authMiddleware.js
- backend/src/utils/errorKodovi.js
- backend/src/utils/userTypeMiddleWare.js
- backend/src/viewModels/korisnikViewModel.js
- frontend/src/redux/userSlice.js
- frontend/src/viewModels/useLogin.js
- frontend/src/views/Login.jsx
- frontend/src/views/Raspored.jsx
Sad se pri prijavi dobiva i JWT koji vrijedi i poslije refreshanja rasporeda. Sve lozinke u mock podacima su hashirane, pa se uspoređuju sa podacima unesenim u formu pri loginu, pa bi se trebala updateati baza. Dodan .env file koji omogućava dodatnu sigurnost podataka i lakše mijenjanje varijabli u kodu ovisno o enviromentu. Ne pusha se .env file iz backenda nego imate .env.example koji ima primjer onoga što vi trebate imati u svojoj lokalno kreiranoj .env datoteci.
> Funkcionalan JWT, bcrypt hashiranje mock podataka, .env varijable

- frontend/src/css/Raspored.css
- frontend/src/viewModels/useLogin.js
- frontend/src/views/Raspored.jsx
promjena termina dodavanje kolokvija ...jel to bia problem
> prof funkc

- backend/package-lock.json
- backend/package.json
- backend/src/routes/korisnikRoutes.js
- backend/src/utils/authMiddleware.js
- backend/src/utils/errorKodovi.js
- backend/src/viewModels/korisnikViewModel.js
- frontend/src/viewModels/useLogin.js
- frontend/src/views/Raspored.jsx
Rade refreshovi s JWT-om opet, ali bez hashiranja sad. Malo promijenjen i prikaz rasporeda.
> Refresh update
